name: "CI"

on:
  push:
    branches:
      - main
    paths:
      - "api/**"
      - ".github/workflows/ci.yml"

jobs:
  build:
    name: "API"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar pnpm
        run: npm install -g pnpm

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.11.0
          cache: pnpm
          cache-dependency-path: api/pnpm-lock.yaml

      - name: Instalar dependências
        run: pnpm install
        working-directory: api

      - name: Rodar testes
        run: pnpm run test
        working-directory: api
